import { PARAM_FIELDS } from '../src/params.js'
import { observe, silenced } from '../src/observed.js'
import { couplingFor } from '../src/coupling.js'

const RATIOS = PARAM_FIELDS.find((f) => f.key === 'aspect_ratio').options
const list = (xs) => (xs.length ? xs.map((x) => `\`${x}\``).join(', ') : '—')

/**
 * What each model actually returns, decoded from the returned bytes rather than
 * assumed from the request — including the parameters measured to have no
 * effect at all, which are hidden in the app rather than offered as choices.
 */
export function formatsNote({ images, caps, stamp }) {
  const models = [...new Set(images.map((i) => i.model))].sort()

  const seen = models.map((m) => {
    const runs = images.filter((i) => i.model === m)
    const unusable = new Set(
      caps
        .filter((c) => c.model === m && (c.verdict === 'rejected' || c.verdict === 'ignored'))
        .map((c) => `${c.param}::${c.value}`)
    )
    const facts = observe(runs)
    const hidden = silenced(facts, unusable)
    for (const [param, reason] of hidden) {
      if (reason.kind === 'dead') reason.coupling = couplingFor(param, runs)
    }
    return { m, facts, hidden }
  })

  const fixed = seen.flatMap(({ m, hidden, facts }) =>
    [...hidden.entries()].map(([param, r]) => ({
      m,
      param,
      value:
        r.kind === 'dead'
          ? r.coupling
            ? `whatever ${r.coupling.driver} implies`
            : 'nothing you ask for'
          : r.value,
      why:
        r.kind === 'fixed'
          ? `asked ${list(r.fact.contradicted)} across ${r.fact.samples} images; all came back ${r.value}`
          : r.kind === 'sole'
            ? `${list(r.dead)} measured rejected or ignored, leaving nothing to choose`
            : r.coupling
              ? `ignored, but every image matched its ${r.coupling.driver}: ${r.coupling.map
                  .map(([from, to]) => `\`${from}\` → \`${to}\``)
                  .join(', ')}`
              : `every value offered was ignored or rejected; returned ${list([
                  ...facts[param].produced.keys(),
                ])}`,
    }))
  )

  return `# Formats and aspect ratios

What each model actually returned, decoded from the returned bytes rather than
assumed from the request. Regenerated by \`npm run vault\`.

_Last synced: ${stamp}_

## Parameters with no choice in them

A model that returns the same thing whatever you ask is not offering a control.
These are hidden in Atelier-1111 rather than shown as options that do nothing —
a request that is silently overridden still bills in full.

| Model | Parameter | Always returns | Evidence |
|---|---|---|---|
${fixed.map((f) => `| \`${f.m}\` | ${f.param} | **${f.value}** | ${f.why} |`).join('\n') || '| — | — | — | _none measured yet_ |'}

> [!note] Two runs minimum
> A single image is never enough to call a parameter fixed — the model may
> simply have defaulted. The claim needs at least two images that agree *and*
> at least one run that asked for something else and did not get it.

## Formats returned

| Model | Asked for | Returned | Asked but never returned |
|---|---|---|---|
${seen
  .map(({ m, facts }) => {
    const f = facts.output_format
    return `| \`${m}\` | ${list([...f.asked])} | ${list([...f.produced.keys()])} | ${list(f.refused)} |`
  })
  .join('\n')}

> [!note] A substituted format still bills in full
> A model that quietly returns a different format looks like success. It is only
> detectable by reading the returned bytes. The SVG case first showed up as a
> broken image, because the file had been saved with a \`.png\` extension and was
> therefore served as \`image/png\`.

## Aspect ratios

Produced means an image actually came back at that ratio. **Never produced**
means it was requested and something else arrived — the only way to learn that a
model will not draw a shape. Everything else is simply untested.

| Model | Produced | Never produced | Untested |
|---|---|---|---|
${seen
  .map(({ m, facts }) => {
    const f = facts.aspect_ratio
    const made = [...f.produced.keys()]
    const untested = RATIOS.filter((r) => !made.includes(r) && !f.refused.includes(r))
    return `| \`${m}\` | ${list(made)} | ${list(f.refused)} | ${list(untested)} |`
  })
  .join('\n')}

**Ratios exercised anywhere so far:** ${list([
    ...new Set(seen.flatMap(({ facts }) => [...facts.aspect_ratio.produced.keys()])),
  ].sort())}

## Resolution

| Model | Produced | Asked but never produced |
|---|---|---|
${seen
  .map(({ m, facts }) => {
    const f = facts.resolution
    return `| \`${m}\` | ${list([...f.produced.keys()])} | ${list(f.refused)} |`
  })
  .join('\n')}

## See also
- [[Image models — measured]]
- [[Parameter support]]
`
}
