/**
 * The corpus note: completion time, cost and failure modes per model, all
 * derived from job timestamps and the API's own usage report.
 */
import { isModeration } from '../src/moderation.js'

const secs = (v) => (v == null ? '—' : `${v.toFixed(1)}s`)
const usd = (v) => (v == null ? '—' : `$${v.toFixed(4)}`)

/** Per-model timing, cost and failure roll-up. Shared with the lineage note. */
export function perModel({ jobs, images, models }) {
  return models.map((m) => {
    const js = jobs.filter((j) => j.model === m)
    const done = js.filter((j) => j.status === 'done' && j.finished_at)
    const errs = js.filter((j) => j.status === 'error')
    const ims = images.filter((i) => i.model === m)
    const durs = done.map((j) => (j.finished_at - j.created_at) / 1000).sort((a, b) => a - b)
    const costs = ims.map((i) => i.cost).filter((c) => c != null)

    return {
      m,
      runs: js.length,
      ok: done.length,
      fail: errs.length,
      avg: durs.length ? durs.reduce((a, b) => a + b, 0) / durs.length : null,
      lo: durs[0] ?? null,
      hi: durs[durs.length - 1] ?? null,
      cost: costs.length ? costs.reduce((a, b) => a + b, 0) / costs.length : null,
      fmts: [...new Set(ims.map((i) => i.format).filter(Boolean))],
      dims: [...new Set(ims.map((i) => (i.width && i.height ? `${i.width}×${i.height}` : null)).filter(Boolean))],
      errs: [...new Set(errs.filter((e) => !isModeration(e.error)).map((e) => (e.error || '').slice(0, 70)))],
      blocked: errs.filter((e) => isModeration(e.error)).length,
    }
  })
}

export function indexNote({ jobs, images, models, stamp }) {
  const rows = perModel({ jobs, images, models })
  const withRuns = rows.filter((r) => r.ok)
  const sample = (r) => (r.ok > 1 ? ` ⟨n=${r.ok}⟩` : ' ⟨n=1⟩')

  return `# Image models — measured

Observed behaviour of OpenRouter image models, run through **Atelier-1111**.
Every figure here was measured from a real response; none is copied from a spec
sheet. Regenerated by \`npm run vault\` — do not hand-edit.

- Corpus: **${jobs.length} jobs**, **${images.length} images**, **${models.length} models**
- Last synced: ${stamp}
- Source: \`CODE/Atelier-1111\` → \`data/atelier.db\`

## Completion time and cost

| Model | Runs | OK | Failed | Avg time | Range | Avg cost/image | Returns |
|---|---:|---:|---:|---:|---|---:|---|
${rows
  .slice()
  .sort((a, b) => (a.avg == null) - (b.avg == null) || (a.avg ?? 0) - (b.avg ?? 0))
  .map(
    (r) =>
      `| \`${r.m}\` | ${r.runs} | ${r.ok} | ${r.fail} | ${secs(r.avg)}${r.ok ? sample(r) : ''} | ${
        r.ok > 1 ? `${secs(r.lo)}–${secs(r.hi)}` : '—'
      } | ${usd(r.cost)} | ${r.fmts.join(', ') || '—'} |`
  )
  .join('\n')}

> [!warning] Sample size
> Most models have been run only a handful of times. A single timing is a data
> point, not an average — generation time varies with prompt, resolution and
> provider load. Costs are firmer, coming from the API's usage report rather
> than from estimation.

## Fastest first

| # | Model | Avg | Cost |
|---:|---|---:|---:|
${withRuns
  .slice()
  .sort((a, b) => a.avg - b.avg)
  .map((r, i) => `| ${i + 1} | \`${r.m}\` | ${secs(r.avg)} | ${usd(r.cost)} |`)
  .join('\n')}

## Cheapest first

| # | Model | Cost | Avg |
|---:|---|---:|---:|
${withRuns
  .filter((r) => r.cost != null)
  .sort((a, b) => a.cost - b.cost)
  .map((r, i) => `| ${i + 1} | \`${r.m}\` | ${usd(r.cost)} | ${secs(r.avg)} |`)
  .join('\n')}

## Known failure modes

${rows
  .filter((r) => r.errs.length)
  .map((r) => `- \`${r.m}\` — ${r.errs.map((e) => `\`${e}\``).join('; ')}`)
  .join('\n') || '_None recorded._'}

## Content refusals

Counted apart from failures: these are a verdict on one prompt or one reference
image, not on the model, and they are **not deterministic** — riverflow-v2.5-pro
and gemini-3.1-flash-lite each refused a request and then completed the
identical request seconds later. Every provider words it differently and none
returns a distinct status code.

| Model | Blocked |
|---|---:|
${rows.filter((r) => r.blocked).map((r) => `| \`${r.m}\` | ${r.blocked} |`).join('\n') || '| — | 0 |'}

> [!important] The 60-second wall was a VPN, not a model
> Every request lasting over 60s once died at exactly 60.0s with
> \`UND_ERR_SOCKET: other side closed\` and no response headers. It looked
> model-specific; it was not. The same 60s cut hit \`httpbin.org\`, an unrelated
> host, which is what gave it away. **Turning the VPN off resolved it** — runs
> then completed at 68.3s and 117.4s.
>
> Timings recorded while the VPN was active are therefore unreliable, and any
> pre-fix failure says nothing about the model.

## See also
- [[Lineage and supersession]]
- [[Formats and aspect ratios]]
- [[Parameter support]]
`
}
