/**
 * The lineage note.
 *
 * Unlike the other three vault notes, most of this is written rather than
 * derived: which model replaces which is computable from the ids, but *why*
 * two similarly-named models are different products is only visible in the
 * vendor descriptions. That reasoning is recorded here so it survives a
 * regeneration and does not have to be re-derived.
 */

export function lineageNote({ retired, stamp, total, current, measured = new Map() }) {
  // Measured rows for the Gemini family, so the vendor's claims can be checked
  // against what actually came back rather than repeated.
  const seen = (id) => measured.get(id)
  const cell = (id, pick) => {
    const r = seen(id)
    return r ? pick(r) : '—'
  }
  const nb2 = seen('google/gemini-3.1-flash-image')
  const nbPro = seen('google/gemini-3-pro-image')
  const table = [...retired]
    .sort()
    .map(([id, by]) => `| \`${id}\` | \`${by}\` |`)
    .join('\n')

  return `# Lineage and supersession

Which image models replace which, and — more importantly — which ones only
*look* like they do. Regenerated by \`npm run vault\`; the prose sections are
authored and carry across regenerations.

_Last synced: ${stamp} · ${current} current of ${total} listed_

## Retired

A model is retired only when a higher version of the **same vendor, family and
tier** exists. Tiers are separate products, not generations — flash, pro, max,
mini, turbo, lite, vector and utility coexist deliberately and never displace
one another. A \`-preview\` retires the moment its stable twin appears.

| Retired | Replaced by |
|---|---|
${table}

## OpenAI ships two image lines, not one

This is the trap. \`gpt-image-1-mini\` and \`gpt-5-image-mini\` look like the same
product a generation apart. They are not.

**Line A — bare image endpoints** (\`text+image->image\`), the dedicated Images API:

| Model | Image-out rate | Vendor description |
|---|---|---|
| \`gpt-image-1\` | $40/M | generates and edits via the Images API |
| \`gpt-image-1-mini\` | $8/M | "a cost-efficient **variant of GPT Image 1**" |
| \`gpt-image-2\` | $30/M | "OpenAI's **latest** image generation model" |

**Line B — GPT-N reasoning models with an image engine attached**
(\`text+image+file->text+image\`):

| Model | Wraps | Vendor description |
|---|---|---|
| \`gpt-5-image\` | GPT Image 1 | "combines **GPT-5** … incorporating **GPT Image 1's** instruction following" |
| \`gpt-5-image-mini\` | GPT Image 1 Mini | "combines **GPT-5 Mini** with **GPT Image 1 Mini**" |
| \`gpt-5.4-image-2\` | GPT Image 2 | "combines **GPT-5.4** … from **GPT Image 2**" |

Line B **wraps** Line A rather than replacing it. So:

- \`gpt-5-image-mini\` does **not** supersede \`gpt-image-1-mini\` — it contains it.
- \`gpt-image-1-mini\` survives because OpenAI has shipped no \`gpt-image-2-mini\`.
- \`gpt-5-image\` **is** retired by \`gpt-5.4-image-2\`: same line, newer LLM *and*
  newer image engine. The trailing \`-2\` is the engine version, not a tier, which
  is why the parser treats \`image-2\` and \`image\` as one tier.

> [!warning] \`created\` is a listing date, not a release date
> All three \`gpt-image-*\` models share an identical \`created\` timestamp — they
> were listed in one batch. The **Released** column in the model card inherits
> this, so for that family it says nothing about which model came first.

## Google: the Nano Banana family

Every Google image model is a Nano Banana under a Gemini codename. The marketing
name is the clearer guide to what each one is for.

| Model | Marketing name | Image-out | Context | Role |
|---|---|---|---|---|
| \`gemini-2.5-flash-image\` | Nano Banana | $30/M | 32K | **retired** — first generation |
| \`gemini-3-pro-image\` | Nano Banana Pro | $120/M | 131K | highest quality, built on Gemini 3 Pro |
| \`gemini-3.1-flash-image\` | Nano Banana 2 | $60/M | 131K | "**Pro-level visual quality at Flash speed**" |
| \`gemini-3.1-flash-lite-image\` | Nano Banana 2 Lite | $30/M | 65K | fastest and cheapest |

### Measured, not claimed

| Model | Time | Cost/image | Returned |
|---|---:|---:|---|
| \`gemini-3-pro-image\` (NB Pro) | ${cell('google/gemini-3-pro-image', (r) => `${r.avg.toFixed(1)}s`)} | ${cell('google/gemini-3-pro-image', (r) => `$${r.cost.toFixed(4)}`)} | ${cell('google/gemini-3-pro-image', (r) => r.fmts.join(', '))} |
| \`gemini-3.1-flash-image\` (NB 2) | ${cell('google/gemini-3.1-flash-image', (r) => `${r.avg.toFixed(1)}s`)} | ${cell('google/gemini-3.1-flash-image', (r) => `$${r.cost.toFixed(4)}`)} | ${cell('google/gemini-3.1-flash-image', (r) => r.fmts.join(', '))} |
${
  nb2 && nbPro
    ? `
Nano Banana 2 came back **${(nbPro.avg / nb2.avg).toFixed(1)}× faster** at
**${((1 - nb2.cost / nbPro.cost) * 100).toFixed(0)}% lower cost** than Nano Banana Pro on the same
prompt — matching the published $60/M vs $120/M rate ratio. Visual quality was
not compared; that still needs a side-by-side on identical seeds and prompt.
`
    : ''
}
> [!caution] Nano Banana 2 silently returns JPEG
> Asked for \`png\`, it delivered \`jpeg\` — recorded as \`ignored\` in the ledger.
> That is lossy output where lossless was requested, and it bills in full. Use
> \`gemini-3-pro-image\` when PNG actually matters; it honours the request.

Two things worth acting on:

1. **Nano Banana 2 is the value pick, measured.** Faster and cheaper than Pro on
   real runs. Quality is the open question, not price.
2. **3.1 Flash supersedes 2.5 Flash, not 3 Pro.** They are different tiers —
   \`flash-image\` and \`pro-image\` — so both stay. Only the 2.5 generation retires.

The previews retire on more than naming: both stable releases doubled the
context window their previews shipped with (65K → 131K), at identical pricing.

## See also
- [[Image models — measured]]
- [[Formats and aspect ratios]]
- [[Parameter support]]
`
}
