#!/usr/bin/env node
/**
 * Regenerate the vault's image-model notes from data/atelier.db.
 *
 * Everything published is measured — completion times from job timestamps,
 * costs from the API's own usage report, formats and dimensions decoded from
 * the returned bytes. Nothing is transcribed by hand, so re-running after a
 * batch of generations is the whole update process.
 *
 *   VAULT_DIR="/path/to/vault/image models" npm run vault
 *
 * VAULT_DIR can also live in .env.
 */
import { writeFileSync, mkdirSync } from 'node:fs'
import { join } from 'node:path'
import { db } from '../server/db/index.js'
import { findSuperseded } from '../server/supersede.js'
import { lineageNote } from './lineage-note.mjs'
import { formatsNote } from './formats-note.mjs'
import { indexNote, perModel } from './index-note.mjs'
import { videoNote } from './video-note.mjs'

const VAULT = process.env.VAULT_DIR
if (!VAULT) {
  console.error('[vault] set VAULT_DIR to the folder the notes should be written to.')
  process.exit(1)
}
mkdirSync(VAULT, { recursive: true })

// Scoped to stills. Video has its own endpoint, parameters and price model,
// and folding one clip into the image tables would misreport both.
const jobs = db.prepare("SELECT * FROM jobs WHERE kind = 'image'").all()
const images = db.prepare("SELECT * FROM images WHERE kind = 'image'").all().map((i) => ({
  ...i,
  params: JSON.parse(i.params || '{}'),
}))
const caps = db.prepare('SELECT * FROM capabilities ORDER BY model, param, value').all()

const stamp = new Date().toISOString().slice(0, 10)

const models = [...new Set([...jobs.map((j) => j.model), ...images.map((i) => i.model)])].sort()

/* ── 1. index ─────────────────────────────────────────────────────────── */

const index = indexNote({ jobs, images, models, stamp })

/* ── 2. formats and aspect ratios ─────────────────────────────────────── */

const formats = formatsNote({ images, caps, stamp })

/* ── 3. parameter support ─────────────────────────────────────────────── */

const params = `# Parameter support

OpenRouter publishes **no** support data for \`aspect_ratio\`, \`resolution\`,
\`quality\` or \`output_format\` — its \`supported_parameters\` field covers chat
sampling only. Every verdict below was observed from a real response.
Regenerated by \`npm run vault\`.

_Last synced: ${stamp}_

| Verdict | Meaning |
|---|---|
| \`ok\` | Sent, and the output matched the request |
| \`ignored\` | Sent, accepted, quietly overridden — **billed in full** |
| \`rejected\` | The API errored naming it (a 400, so nothing was billed) |
| \`unverifiable\` | Accepted, but leaves no trace in the output (\`quality\`) |

## Observed verdicts

| Model | Parameter | Value | Verdict | Evidence |
|---|---|---|---|---|
${caps
  .map((c) => `| \`${c.model}\` | ${c.param} | ${c.value} | ${c.verdict} | ${c.evidence || ''} |`)
  .join('\n')}

## See also
- [[Image models — measured]]
- [[Formats and aspect ratios]]
`

/* ── 4. lineage ───────────────────────────────────────────────────────── */

// Supersession is computed from the ids of every model ever seen here, so the
// note stays right without a hand-maintained retire list.
const seenIds = models.map((id) => ({ id }))
const retired = findSuperseded(seenIds)
const measured = new Map(
  perModel({ jobs, images, models })
    .filter((r) => r.ok && r.cost != null)
    .map((r) => [r.m, r])
)

writeFileSync(
  join(VAULT, 'Lineage and supersession.md'),
  lineageNote({
    retired,
    stamp,
    total: seenIds.length,
    current: seenIds.length - retired.size,
    measured,
  })
)

// Video is measured separately — different endpoint, different economics.
const videoJobs = db.prepare("SELECT * FROM jobs WHERE kind = 'video'").all()
const videoImages = db.prepare("SELECT * FROM images WHERE kind = 'video'").all()
if (videoJobs.length) {
  writeFileSync(
    join(VAULT, 'Video models — measured.md'),
    videoNote({ jobs: videoJobs, images: videoImages, caps, stamp })
  )
}

writeFileSync(join(VAULT, 'Image models — measured.md'), index)
writeFileSync(join(VAULT, 'Formats and aspect ratios.md'), formats)
writeFileSync(join(VAULT, 'Parameter support.md'), params)

console.log(`[vault] synced ${videoJobs.length ? 5 : 4} notes to ${VAULT}`)
console.log(
  `[vault] ${jobs.length} image jobs · ${images.length} images · ${videoJobs.length} video jobs · ${videoImages.length} clips · ${caps.length} verdicts`
)
