const usd = (v) => (v == null ? '—' : `$${v.toFixed(3)}`)
const secs = (v) => (v == null ? '—' : `${v.toFixed(0)}s`)
const VIDEO_PARAMS = new Set(['aspect_ratio', 'resolution', 'duration', 'generate_audio'])

/**
 * Video models, measured. Kept apart from the image notes because almost
 * nothing transfers: a different endpoint, an asynchronous job, no published
 * price, and a cost per attempt roughly sixty times higher.
 */
export function videoNote({ jobs, images, caps, stamp }) {
  const models = [...new Set(jobs.map((j) => j.model))].sort()

  const rows = models.map((m) => {
    const js = jobs.filter((j) => j.model === m)
    const done = js.filter((j) => j.status === 'done' && j.finished_at)
    const ims = images.filter((i) => i.model === m)
    const durs = done.map((j) => (j.finished_at - j.created_at) / 1000)
    const costs = ims.map((i) => i.cost).filter((c) => c != null)

    return {
      m,
      runs: js.length,
      ok: done.length,
      fail: js.filter((j) => j.status === 'error').length,
      wait: durs.length ? durs.reduce((a, b) => a + b, 0) / durs.length : null,
      cost: costs.length ? costs.reduce((a, b) => a + b, 0) / costs.length : null,
      sizes: [...new Set(ims.map((i) => `${i.width}×${i.height}`))],
      lengths: [...new Set(ims.map((i) => i.seconds).filter(Boolean))].sort((a, b) => a - b),
      mb: ims.length
        ? ims.reduce((s, i) => s + i.bytes, 0) / ims.length / 1048576
        : null,
    }
  })

  const verdicts = caps.filter((c) => VIDEO_PARAMS.has(c.param) && models.includes(c.model))
  const audio = caps.filter((c) => c.param === 'generate_audio')

  return `# Video models — measured

Observed behaviour of OpenRouter's video models, run through **Atelier-1111**.
Regenerated by \`npm run vault\` — do not hand-edit.

- Corpus: **${jobs.length} jobs**, **${images.length} clips**, **${models.length} models**
- Last synced: ${stamp}

> [!important] Video is a different pipeline, not a variant of images
> \`POST /api/v1/videos\` answers **202** with a polling URL and finishes minutes
> later; the bytes come from a third call. There is no batch parameter, no
> streaming, and **no published price** — every video model reports \`0/0\`, so
> cost is only ever known after the fact, from the usage report.

## Cost and wait

| Model | Runs | OK | Failed | Avg wait | Avg cost | Sizes returned | Lengths | Avg file |
|---|---:|---:|---:|---:|---:|---|---|---:|
${rows
  .sort((a, b) => (a.cost ?? 9) - (b.cost ?? 9))
  .map(
    (r) =>
      `| \`${r.m}\` | ${r.runs} | ${r.ok} | ${r.fail} | ${secs(r.wait)} | ${usd(r.cost)} | ${
        r.sizes.join(', ') || '—'
      } | ${r.lengths.map((l) => `${l}s`).join(', ') || '—'} | ${
        r.mb ? `${r.mb.toFixed(1)} MB` : '—'
      } |`
  )
  .join('\n')}

> [!warning] One clip is one data point
> Cost varies with length and resolution, and most of these models have been run
> once or twice. Treat the column as an order of magnitude.

## Supported values, published in rejections

A refused parameter costs nothing and providers usually name the whole legal
set — the closest thing to documentation these models have.

| Model | Parameter | Refused | Provider says |
|---|---|---|---|
${verdicts
  .filter((c) => c.verdict === 'rejected')
  .map((c) => {
    const accepted = /Accepted: ([^.]+)\./.exec(c.evidence || '')?.[1]
    return `| \`${c.model}\` | ${c.param} | \`${c.value}\` | ${accepted ? `**${accepted}**` : c.evidence?.slice(0, 60)} |`
  })
  .join('\n') || '| — | — | — | _none recorded_ |'}

## Every measured verdict

| Model | Parameter | Value | Verdict | Evidence |
|---|---|---|---|---|
${verdicts
  .map(
    (c) =>
      `| \`${c.model}\` | ${c.param} | ${c.value} | ${c.verdict} | ${String(c.evidence || '')
        .replace(/\s+/g, ' ')
        .slice(0, 90)} |`
  )
  .join('\n')}

## Audio

\`generate_audio\` is one of the few flags in this app that can be checked
outright: a silent MP4 carries no \`soun\` track. Every run so far asked for
**no** audio.

| Model | Honoured the request? |
|---|---|
${audio
  .map((c) => `| \`${c.model}\` | ${c.verdict === 'ok' ? 'yes — silent' : '**no — added a sound track anyway**'} |`)
  .join('\n') || '| — | — |'}

## See also
- [[Image models — measured]]
`
}
